trials = [
    {
        "Trial": "1",
        "Img": "1_sb10-a_3.jpg",
        "Target": "sb10-a",
        "CorrRes": "3",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb8-a",
        "Foil2": "sb30-a"
    },
    {
        "Trial": "2",
        "Img": "2_sb16-b_2.jpg",
        "Target": "sb16-b",
        "CorrRes": "2",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb40-a",
        "Foil2": "sb52-b"
    },
    {
        "Trial": "3",
        "Img": "3_sb22-a_1.jpg",
        "Target": "sb22-a",
        "CorrRes": "1",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb58-a",
        "Foil2": "sb60-b"
    },
    {
        "Trial": "4",
        "Img": "4_sb66-b_3.jpg",
        "Target": "sb66-b",
        "CorrRes": "3",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb64-b",
        "Foil2": "sb56-b"
    },
    {
        "Trial": "5",
        "Img": "5_sb70-a_1.jpg",
        "Target": "sb70-a",
        "CorrRes": "1",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb63-a",
        "Foil2": "sb54-b"
    },
    {
        "Trial": "6",
        "Img": "6_sb82-b_2.jpg",
        "Target": "sb82-b",
        "CorrRes": "2",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb61-b",
        "Foil2": "sb79-a"
    },
    {
        "Trial": "7",
        "Img": "7_sb22-a_3.jpg",
        "Target": "sb22-a",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb2-a",
        "Foil2": "sb4-b"
    },
    {
        "Trial": "8",
        "Img": "8_sb82-b_3.jpg",
        "Target": "sb82-b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb6-b",
        "Foil2": "sb12-b"
    },
    {
        "Trial": "9",
        "Img": "9_sb70-a_2.jpg",
        "Target": "sb70-a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb18-a",
        "Foil2": "sb20-a"
    },
    {
        "Trial": "10",
        "Img": "10_sb10-a_1.jpg",
        "Target": "sb10-a",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb28-a",
        "Foil2": "sb36-b"
    },
    {
        "Trial": "11",
        "Img": "11_sb16-b_1.jpg",
        "Target": "sb16-b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb84-a",
        "Foil2": "sb44-b"
    },
    {
        "Trial": "12",
        "Img": "12_sb66-b_2.jpg",
        "Target": "sb66-b",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb65-a",
        "Foil2": "sb72-b"
    },
    {
        "Trial": "13",
        "Img": "13_sb70-a_1.jpg",
        "Target": "sb70-a",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb24-a",
        "Foil2": "sb42-b"
    },
    {
        "Trial": "14",
        "Img": "14_sb10-a_3.jpg",
        "Target": "sb10-a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb68-a",
        "Foil2": "sb69-a"
    },
    {
        "Trial": "15",
        "Img": "15_sb16-b_1.jpg",
        "Target": "sb16-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb80-a",
        "Foil2": "sb24-b"
    },
    {
        "Trial": "16",
        "Img": "16_sb22-a_2.jpg",
        "Target": "sb22-a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb68-b",
        "Foil2": "sb81-a"
    },
    {
        "Trial": "17",
        "Img": "17_sb66-b_2.jpg",
        "Target": "sb66-b",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb42-a",
        "Foil2": "sb69-b"
    },
    {
        "Trial": "18",
        "Img": "18_sb82-b_3.jpg",
        "Target": "sb82-b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "sb81-b",
        "Foil2": "sb80-b"
    },
    {
        "Trial": "19",
        "Img": "19_sb66-b_2.jpg",
        "Target": "sb66-b",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb69-b",
        "Foil2": "sb42-b"
    },
    {
        "Trial": "20",
        "Img": "20_sb70-a_3.jpg",
        "Target": "sb70-a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb24-a",
        "Foil2": "sb81-b"
    },
    {
        "Trial": "21",
        "Img": "21_sb16-b_1.jpg",
        "Target": "sb16-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb69-a",
        "Foil2": "sb68-a"
    },
    {
        "Trial": "22",
        "Img": "22_sb22-a_1.jpg",
        "Target": "sb22-a",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb24-b",
        "Foil2": "sb80-a"
    },
    {
        "Trial": "23",
        "Img": "23_sb82-b_2.jpg",
        "Target": "sb82-b",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb42-a",
        "Foil2": "sb81-a"
    },
    {
        "Trial": "24",
        "Img": "24_sb10-a_3.jpg",
        "Target": "sb10-a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "sb80-b",
        "Foil2": "sb68-b"
    },
    {
        "Trial": "25",
        "Img": "25_sb66-a_2.jpg",
        "Target": "sb66-a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb72-a",
        "Foil2": "sb44-a"
    },
    {
        "Trial": "26",
        "Img": "26_sb22-b_3.jpg",
        "Target": "sb22-b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb2-b",
        "Foil2": "sb6-a"
    },
    {
        "Trial": "27",
        "Img": "27_sb10-b_1.jpg",
        "Target": "sb10-b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb65-b",
        "Foil2": "sb84-b"
    },
    {
        "Trial": "28",
        "Img": "28_sb70-b_1.jpg",
        "Target": "sb70-b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb4-a",
        "Foil2": "sb12-a"
    },
    {
        "Trial": "29",
        "Img": "29_sb82-a_1.jpg",
        "Target": "sb82-a",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb18-b",
        "Foil2": "sb28-b"
    },
    {
        "Trial": "30",
        "Img": "30_sb16-a_2.jpg",
        "Target": "sb16-a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb20-b",
        "Foil2": "sb36-a"
    },
    {
        "Trial": "31",
        "Img": "31_sb66-a_2.jpg",
        "Target": "sb66-a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb80-b",
        "Foil2": "sb69-b"
    },
    {
        "Trial": "32",
        "Img": "32_sb82-a_2.jpg",
        "Target": "sb82-a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb24-a",
        "Foil2": "sb68-a"
    },
    {
        "Trial": "33",
        "Img": "33_sb70-b_3.jpg",
        "Target": "sb70-b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb81-b",
        "Foil2": "sb42-a"
    },
    {
        "Trial": "34",
        "Img": "34_sb10-b_1.jpg",
        "Target": "sb10-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb80-a",
        "Foil2": "sb68-b"
    },
    {
        "Trial": "35",
        "Img": "35_sb22-b_1.jpg",
        "Target": "sb22-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb81-a",
        "Foil2": "sb24-b"
    },
    {
        "Trial": "36",
        "Img": "36_sb16-a_3.jpg",
        "Target": "sb16-a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "sb42-b",
        "Foil2": "sb69-a"
    },
    {
        "Trial": "37",
        "Img": "37_sb82-a_3.jpg",
        "Target": "sb82-a",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb2-a",
        "Foil2": "sb72-b"
    },
    {
        "Trial": "38",
        "Img": "38_sb10-b_2.jpg",
        "Target": "sb10-b",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb4-b",
        "Foil2": "sb65-a"
    },
    {
        "Trial": "39",
        "Img": "39_sb22-b_3.jpg",
        "Target": "sb22-b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb6-b",
        "Foil2": "sb44-b"
    },
    {
        "Trial": "40",
        "Img": "40_sb66-a_2.jpg",
        "Target": "sb66-a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb12-b",
        "Foil2": "sb84-a"
    },
    {
        "Trial": "41",
        "Img": "41_sb70-b_1.jpg",
        "Target": "sb70-b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb18-a",
        "Foil2": "sb36-b"
    },
    {
        "Trial": "42",
        "Img": "42_sb16-a_1.jpg",
        "Target": "sb16-a",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb28-a",
        "Foil2": "sb20-a"
    },
    {
        "Trial": "43",
        "Img": "43_sb66-a_2.jpg",
        "Target": "sb66-a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb80-b",
        "Foil2": "sb42-b"
    },
    {
        "Trial": "44",
        "Img": "44_sb16-a_2.jpg",
        "Target": "sb16-a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb69-b",
        "Foil2": "sb24-b"
    },
    {
        "Trial": "45",
        "Img": "45_sb82-a_3.jpg",
        "Target": "sb82-a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb81-b",
        "Foil2": "sb80-a"
    },
    {
        "Trial": "46",
        "Img": "46_sb70-b_1.jpg",
        "Target": "sb70-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb68-a",
        "Foil2": "sb42-a"
    },
    {
        "Trial": "47",
        "Img": "47_sb10-b_3.jpg",
        "Target": "sb10-b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb24-a",
        "Foil2": "sb81-a"
    },
    {
        "Trial": "48",
        "Img": "48_sb22-b_1.jpg",
        "Target": "sb22-b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "sb68-b",
        "Foil2": "sb69-a"
    }
]
