trials = [
    {
        "Trial": "1",
        "Img": "1_nz1-4-a_1.jpg",
        "Target": "nz1_4_a",
        "CorrRes": "1",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_14_a",
        "Foil2": "nz1_38_a"
    },
    {
        "Trial": "2",
        "Img": "2_nz1-12-b_3.jpg",
        "Target": "nz1_12_b",
        "CorrRes": "3",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_34_b",
        "Foil2": "nz1_40_b"
    },
    {
        "Trial": "3",
        "Img": "3_nz1-30-a_2.jpg",
        "Target": "nz1_30_a",
        "CorrRes": "2",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_67_a",
        "Foil2": "nz1_61_b"
    },
    {
        "Trial": "4",
        "Img": "4_nz1-75-a_1.jpg",
        "Target": "nz1_75_a",
        "CorrRes": "1",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_42_b",
        "Foil2": "nz1_44_a"
    },
    {
        "Trial": "5",
        "Img": "5_nz1-70-b_2.jpg",
        "Target": "nz1_70_b",
        "CorrRes": "2",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_48_a",
        "Foil2": "nz1_80_b"
    },
    {
        "Trial": "6",
        "Img": "6_nz1-77-b_3.jpg",
        "Target": "nz1_77_b",
        "CorrRes": "3",
        "FoilLevel": "1",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_73_a",
        "Foil2": "nz1_74_b"
    },
    {
        "Trial": "7",
        "Img": "7_nz1-30-a_2.jpg",
        "Target": "nz1_30_a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_10_a",
        "Foil2": "nz1_16_b"
    },
    {
        "Trial": "8",
        "Img": "8_nz1-77-b_1.jpg",
        "Target": "nz1_77_b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_18_b",
        "Foil2": "nz1_20_a"
    },
    {
        "Trial": "9",
        "Img": "9_nz1-70-b_2.jpg",
        "Target": "nz1_70_b",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_22_b",
        "Foil2": "nz1_36_b"
    },
    {
        "Trial": "10",
        "Img": "10_nz1-75-a_3.jpg",
        "Target": "nz1_75_a",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_50_a",
        "Foil2": "nz1_62_b"
    },
    {
        "Trial": "11",
        "Img": "11_nz1-4-a_3.jpg",
        "Target": "nz1_4_a",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_66_a",
        "Foil2": "ng1_72_a"
    },
    {
        "Trial": "12",
        "Img": "12_nz1-12-b_1.jpg",
        "Target": "nz1_12_b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_76_a",
        "Foil2": "nz1_79_b"
    },
    {
        "Trial": "13",
        "Img": "13_nz1-4-a_3.jpg",
        "Target": "nz1_4_a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_78_a",
        "Foil2": "nz1_24_b"
    },
    {
        "Trial": "14",
        "Img": "14_nz1-77-b_2.jpg",
        "Target": "nz1_77_b",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_26_b",
        "Foil2": "nz1_46_b"
    },
    {
        "Trial": "15",
        "Img": "15_nz1-75-a_2.jpg",
        "Target": "nz1_75_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_24_a",
        "Foil2": "nz1_52_b"
    },
    {
        "Trial": "16",
        "Img": "16_nz1-12-b_3.jpg",
        "Target": "nz1_12_b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_46_a",
        "Foil2": "nz1_8_b"
    },
    {
        "Trial": "17",
        "Img": "17_nz1-70-b_1.jpg",
        "Target": "nz1_70_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_52_a",
        "Foil2": "nz1_78_b"
    },
    {
        "Trial": "18",
        "Img": "18_nz1-30-a_1.jpg",
        "Target": "nz1_30_a",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "n",
        "Foil1": "nz1_8_a",
        "Foil2": "nz_26_a"
    },
    {
        "Trial": "19",
        "Img": "19_nz1-12-b_3.jpg",
        "Target": "nz1_12_b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_78_a",
        "Foil2": "nz1_52_a"
    },
    {
        "Trial": "20",
        "Img": "20_nz1-30-a_3.jpg",
        "Target": "nz1_30_a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_24_b",
        "Foil2": "nz1_8_a"
    },
    {
        "Trial": "21",
        "Img": "21_nz1-75-a_1.jpg",
        "Target": "nz1_75_a",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_26_b",
        "Foil2": "nz1_78_b"
    },
    {
        "Trial": "22",
        "Img": "22_nz1-4-a_2.jpg",
        "Target": "nz1_4_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_46_b",
        "Foil2": "nz1_8_b"
    },
    {
        "Trial": "23",
        "Img": "23_nz1-70-b_1.jpg",
        "Target": "nz1_70_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_24_a",
        "Foil2": "nz_26_a"
    },
    {
        "Trial": "24",
        "Img": "24_nz1-77-b_2.jpg",
        "Target": "nz1_77_b",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "s",
        "Noise": "y",
        "Foil1": "nz1_52_b",
        "Foil2": "nz1_46_a"
    },
    {
        "Trial": "25",
        "Img": "25_nz1-12-a_1.jpg",
        "Target": "nz1_12_a",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_16_a",
        "Foil2": "nz1_20_b"
    },
    {
        "Trial": "26",
        "Img": "26_nz1-30-b_3.jpg",
        "Target": "nz1_30_b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_10_b",
        "Foil2": "nz1_18_a"
    },
    {
        "Trial": "27",
        "Img": "27_nz1-77-a_2.jpg",
        "Target": "nz1_77_a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_36_a",
        "Foil2": "nz1_62_a"
    },
    {
        "Trial": "28",
        "Img": "28_nz1-75-b_1.jpg",
        "Target": "nz1_75_b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_66_b",
        "Foil2": "nz1_76_b"
    },
    {
        "Trial": "29",
        "Img": "29_nz1-4-b_3.jpg",
        "Target": "nz1_4_b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_22_a",
        "Foil2": "nz1_50_b"
    },
    {
        "Trial": "30",
        "Img": "30_nz1-70-a_2.jpg",
        "Target": "nz1_70_a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "n",
        "Foil1": "ng1_72_b",
        "Foil2": "nz1_79_a"
    },
    {
        "Trial": "31",
        "Img": "31_nz1-12-a_2.jpg",
        "Target": "nz1_12_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_8_a",
        "Foil2": "nz1_52_a"
    },
    {
        "Trial": "32",
        "Img": "32_nz1-70-a_3.jpg",
        "Target": "nz1_70_a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_24_b",
        "Foil2": "nz1_46_b"
    },
    {
        "Trial": "33",
        "Img": "33_nz1-77-a_2.jpg",
        "Target": "nz1_77_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_78_a",
        "Foil2": "nz1_26_b"
    },
    {
        "Trial": "34",
        "Img": "34_nz1-75-b_3.jpg",
        "Target": "nz1_75_b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_52_b",
        "Foil2": "nz1_8_b"
    },
    {
        "Trial": "35",
        "Img": "35_nz1-4-b_1.jpg",
        "Target": "nz1_4_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_24_a",
        "Foil2": "nz1_46_a"
    },
    {
        "Trial": "36",
        "Img": "36_nz1-30-b_1.jpg",
        "Target": "nz1_30_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "n",
        "Foil1": "nz1_78_b",
        "Foil2": "nz_26_a"
    },
    {
        "Trial": "37",
        "Img": "37_nz1-12-a_3.jpg",
        "Target": "nz1_12_a",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_79_b",
        "Foil2": "nz1_10_a"
    },
    {
        "Trial": "38",
        "Img": "38_nz1-70-a_2.jpg",
        "Target": "nz1_70_a",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_16_b",
        "Foil2": "nz1_76_a"
    },
    {
        "Trial": "39",
        "Img": "39_nz1-77-a_1.jpg",
        "Target": "nz1_77_a",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_20_a",
        "Foil2": "nz1_66_a"
    },
    {
        "Trial": "40",
        "Img": "40_nz1-75-b_2.jpg",
        "Target": "nz1_75_b",
        "CorrRes": "2",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_18_b",
        "Foil2": "ng1_72_a"
    },
    {
        "Trial": "41",
        "Img": "41_nz1-30-b_1.jpg",
        "Target": "nz1_30_b",
        "CorrRes": "1",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_36_b",
        "Foil2": "nz1_50_a"
    },
    {
        "Trial": "42",
        "Img": "42_nz1-4-b_3.jpg",
        "Target": "nz1_4_b",
        "CorrRes": "3",
        "FoilLevel": "2",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_22_b",
        "Foil2": "nz1_62_b"
    },
    {
        "Trial": "43",
        "Img": "43_nz1-12-a_3.jpg",
        "Target": "nz1_12_a",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz_26_a",
        "Foil2": "nz1_52_a"
    },
    {
        "Trial": "44",
        "Img": "44_nz1-77-a_2.jpg",
        "Target": "nz1_77_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_8_a",
        "Foil2": "nz1_78_b"
    },
    {
        "Trial": "45",
        "Img": "45_nz1-4-b_3.jpg",
        "Target": "nz1_4_b",
        "CorrRes": "3",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_46_b",
        "Foil2": "nz1_24_a"
    },
    {
        "Trial": "46",
        "Img": "46_nz1-30-b_1.jpg",
        "Target": "nz1_30_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_26_b",
        "Foil2": "nz1_8_b"
    },
    {
        "Trial": "47",
        "Img": "47_nz1-75-b_1.jpg",
        "Target": "nz1_75_b",
        "CorrRes": "1",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_24_b",
        "Foil2": "nz1_46_a"
    },
    {
        "Trial": "48",
        "Img": "48_nz1-70-a_2.jpg",
        "Target": "nz1_70_a",
        "CorrRes": "2",
        "FoilLevel": "3",
        "View": "d",
        "Noise": "y",
        "Foil1": "nz1_78_a",
        "Foil2": "nz1_52_b"
    }
]